services:
  api:
    platform: linux/amd64
    build:
      context: .
    container_name: blog-recommender
    environment:
      PORT: 8000
    ports:
      - '8080:8080'
    restart: "no"
    env_file: ".env"